Repository edenia/antelope-tools, pull requests merged in 2021-04, with the labels that each got.

#379 feat: add .env.telostestnet
  .env.telostestnet
  .gitignore
  makefile
  webapp/package.json
  webapp/yarn.lock
Labels: enhancement

#381 feat: add telos workflow
  .github/workflows/push-telos-environment.yaml
  webapp/package.json
  webapp/yarn.lock
Labels: devops

#390 properly avoid statefulsets update errors on actions runs.
  .github/workflows/push-dev-environment.yaml
  .github/workflows/push-lacchain-environment.yaml
  .github/workflows/push-master-environment.yaml
  makefile
Labels: devops, enhancement

#397 feat: update prices logic
  .env.telostestnet
  docker-compose.yaml
  hapi/src/config/eos.config.js
  hapi/src/services/setting.service.js
  hasura/metadata/tables.yaml
  hasura/migrations/1606135484776_create_table_public_setting/up.sql
  hasura/migrations/1618439325029_alter_table_public_setting_alter_column_eos_price/down.sql
  hasura/migrations/1618439325029_alter_table_public_setting_alter_column_eos_price/up.sql
  webapp/src/config/eos.config.js
  webapp/src/gql/setting.gql.js
  webapp/src/routes/RewardsDistribution.js
Labels: enhancement, telos, testnet

#421 update: .env.telostestnet
  .env.telostestnet
Labels: bug

#402 Update telos gh workflow
  .github/workflows/push-telos-environment.yaml
Labels: devops

#420 Feat/update prices logic & fix hasura migrations
  .env.jungle
  .env.lacchain
  .env.local
  .env.telostestnet
  .github/workflows/push-dev-environment.yaml
  .github/workflows/push-lacchain-environment.yaml
  .github/workflows/push-master-environment.yaml
  .github/workflows/push-telos-environment.yaml
  docker-compose.yaml
  hapi/src/config/eos.config.js
  hapi/src/services/setting.service.js
  hasura/metadata/tables.yaml
  hasura/migrations/1618439325029_alter_table_public_setting_alter_column_eos_price/down.sql
  hasura/migrations/1618439325029_alter_table_public_setting_alter_column_eos_price/up.sql
  kubernetes/configmap-dashboard.yaml
  webapp/Dockerfile
  webapp/src/config/eos.config.js
  webapp/src/gql/setting.gql.js
  webapp/src/routes/RewardsDistribution.js
Labels: bug
