Repository edenia/antelope-tools, pull requests merged in 2024-07, with the labels that each got.

#1410 Create get block producers script
  hapi/src/config/eos.config.js
  hapi/src/services/cpu.service.js
  hapi/src/services/fio.service.js
  hapi/src/services/fioProducers.js
  hapi/src/services/producer.service.js
  hapi/src/utils/eos.util.js
  hapi/src/utils/producer.util.js
  hasura/migrations/default/1719953232361_alter_table_public_producer_add_column_fio_address/down.sql
  hasura/migrations/default/1719953232361_alter_table_public_producer_add_column_fio_address/up.sql
  hasura/migrations/default/1719953258027_alter_table_public_producer_add_column_addresshash/down.sql
  hasura/migrations/default/1719953258027_alter_table_public_producer_add_column_addresshash/up.sql
  hasura/migrations/default/1719953328741_alter_table_public_producer_add_column_last_bpclaim/down.sql
  hasura/migrations/default/1719953328741_alter_table_public_producer_add_column_last_bpclaim/up.sql
  makefile
  webapp/src/components/ProducersChart/index.js
  webapp/src/gql/producer.gql.js
  webapp/src/routes/Home/BlockProducerInfo.js
Labels: WIP

#1421 feat(webapp): display fio address instead of owner value
  webapp/src/components/GeoMap/CountryMap.js
  webapp/src/components/ProducersChart/index.js
  webapp/src/gql/producer.gql.js
  webapp/src/hooks/customHooks/useEndpointsState.js
  webapp/src/routes/ProducerProfile/ProfileCard.js
Labels: webapp, FIO

#1426 Feat/fio rewards 1416
  .github/workflows/deploy-fio-testnet.yaml
  hapi/src/services/fio.service.js
  hapi/src/services/index.js
  hapi/src/services/producer.service.js
  hapi/src/utils/producer.util.js
  hapi/src/workers/producers.worker.js
  webapp/src/hooks/customHooks/useBlockProducerState.js
  webapp/src/hooks/customHooks/useNonCompliantState.js
  webapp/src/hooks/customHooks/useRewardsDistributionState.js
Labels: enhancement, backend, hoji:reviewed
